# Base configuration for all environments
name = "tamyla-data-service"
main = "src/worker/index.js"
compatibility_date = "2023-07-17"
compatibility_flags = ["nodejs_compat"]

# Default D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "tamyla-auth-db-local"
database_id = "12ef163d-3b44-4b8b-83f0-09b51ef288ab"
migrations_dir = "./migrations"

# Development server configuration
[dev]
port = 3002
ip = "localhost"

# Local development settings
[env.development]
name = "data-service-dev"
main = "src/worker/index.js"
workers_dev = true

# Development D1 Database Binding
[[env.development.d1_databases]]
binding = "DB"
database_name = "tamyla-auth-db-local"
database_id = "12ef163d-3b44-4b8b-83f0-09b51ef288ab"  # ID from our local database
migrations_dir = "./migrations"

# Development environment variables
[env.development.vars]
NODE_ENV = "development"
JWT_SECRET = "dev-secret-key"
BASE_URL = "http://localhost:3002"
FRONTEND_URL = "http://localhost:3000"
MAGIC_LINK_EXPIRY_MINUTES = "15"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX = "100"

# Production environment
[env.production]
name = "data-service"
main = "src/worker/index.js"
workers_dev = true

[[env.production.d1_databases]]
binding = "DB"
database_name = "tamyla-auth-db"
database_id = "373a1466-3086-4132-a4f6-a7b1a64a3a41"
migrations_dir = "./migrations"

[env.production.vars]
NODE_ENV = "production"
JWT_SECRET = "${JWT_SECRET}"
BASE_URL = "https://data-service.tamylatrading.workers.dev"
FRONTEND_URL = "https://app.tamylatrading.com"
MAGIC_LINK_EXPIRY_MINUTES = "15"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX = "100"

# Staging environment
[env.staging]
name = "data-service-staging"
main = "src/worker/index.js"
workers_dev = true

[[env.staging.d1_databases]]
binding = "DB"
database_name = "tamyla-auth-db-staging"
database_id = "373a1466-3086-4132-a4f6-a7b1a64a3a41"
migrations_dir = "./migrations"

[env.staging.vars]
NODE_ENV = "staging"
JWT_SECRET = "${JWT_SECRET}"
BASE_URL = "https://data-service-staging.tamylatrading.workers.dev"
FRONTEND_URL = "https://staging.tamylatrading.com"
MAGIC_LINK_EXPIRY_MINUTES = "15"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX = "100"