# Base configuration for all environments
name = "data-service-dev"  # Default to development
main = "src/worker/index.js"
compatibility_date = "2023-07-17"
compatibility_flags = ["nodejs_compat"]

# Default D1 Database Binding - using development for default deploys
[[d1_databases]]
binding = "DB"
database_name = "tamyla-auth-db-local"
database_id = "12ef163d-3b44-4b8b-83f0-09b51ef288ab"
migrations_dir = "./migrations"

# Default environment variables (development) - ALIGNED WITH SHARED CONFIG
[vars]
NODE_ENV = "development"
SERVICE_NAME = "data-service"
LOG_LEVEL = "info"
AUTH_JWT_SECRET = "d49f3be21dc5ebb3e95e4dfee78f524f8899313ccde1ce362c5df2d33429ad61"
FRONTEND_URL = "http://localhost:3000"
DATA_SERVICE_URL = "http://localhost:3002"
CONTENT_STORE_SERVICE_URL = "http://localhost:3001"
AUTH_SERVICE_URL = "http://localhost:3003"
CORS_ORIGINS = "http://localhost:3000,http://localhost:3001"
MAGIC_LINK_EXPIRY_MINUTES = "15"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX = "100"
MAX_FILE_SIZE = "26214400"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,video/webm,audio/mpeg,audio/wav"
# Security settings
SKIP_WEBHOOK_AUTH = "true"  # Set to false in production
# Service API keys for inter-service communication
CONTENT_SKIMMER_API_KEY = "content-skimmer-dev-key"
LOGGER_SERVICE_API_KEY = "logger-service-dev-key" 
AUTH_SERVICE_API_KEY = "auth-service-dev-key"

# Development server configuration
[dev]
port = 3002
ip = "localhost"

# Local development settings (same as default now)
[env.development]
name = "data-service-dev"
main = "src/worker/index.js"
workers_dev = true

# Development D1 Database Binding (same as default)
[[env.development.d1_databases]]
binding = "DB"
database_name = "tamyla-auth-db-local"
database_id = "12ef163d-3b44-4b8b-83f0-09b51ef288ab"
migrations_dir = "./migrations"

# Development environment variables (aligned with shared config)
[env.development.vars]
NODE_ENV = "development"
SERVICE_NAME = "data-service"
LOG_LEVEL = "info"
AUTH_JWT_SECRET = "d49f3be21dc5ebb3e95e4dfee78f524f8899313ccde1ce362c5df2d33429ad61"
FRONTEND_URL = "http://localhost:3000"
DATA_SERVICE_URL = "http://localhost:3002"
CONTENT_STORE_SERVICE_URL = "http://localhost:3001"
AUTH_SERVICE_URL = "http://localhost:3003"
CORS_ORIGINS = "http://localhost:3000,http://localhost:3001"
MAGIC_LINK_EXPIRY_MINUTES = "15"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX = "100"
MAX_FILE_SIZE = "26214400"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,video/webm,audio/mpeg,audio/wav"

# Staging environment
[env.staging]
name = "data-service-staging"
main = "src/worker/index.js"
workers_dev = true

[[env.staging.d1_databases]]
binding = "DB"
database_name = "tamyla-auth-db-staging"
database_id = "b2d43c7a-dbb9-43b4-afe5-bd0d3c4cf618"
migrations_dir = "./migrations"

[env.staging.vars]
NODE_ENV = "staging"
SERVICE_NAME = "data-service"
LOG_LEVEL = "info"
DATA_SERVICE_URL = "https://data-service-staging.tamylatrading.workers.dev"
CONTENT_STORE_SERVICE_URL = "https://content-staging.tamyla.com"
AUTH_SERVICE_URL = "https://auth-staging.tamyla.com"
FRONTEND_URL = "https://tamyla.com"
CORS_ORIGINS = "https://tamyla.com,https://*.tamyla.com,http://localhost:3000"
MAGIC_LINK_EXPIRY_MINUTES = "15"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX = "100"
MAX_FILE_SIZE = "26214400"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,video/webm,audio/mpeg,audio/wav"

# Production environment
[env.production]
name = "data-service"
main = "src/worker/index.js"
workers_dev = true

[[env.production.d1_databases]]
binding = "DB"
database_name = "tamyla-auth-db"
database_id = "373a1466-3086-4132-a4f6-a7b1a64a3a41"
migrations_dir = "./migrations"

[env.production.vars]
NODE_ENV = "production"
SERVICE_NAME = "data-service"
LOG_LEVEL = "info"
DATA_SERVICE_URL = "https://data-service.tamylatrading.workers.dev"
CONTENT_STORE_SERVICE_URL = "https://content.tamyla.com"
AUTH_SERVICE_URL = "https://auth.tamyla.com"
FRONTEND_URL = "https://tamyla.com"
CORS_ORIGINS = "https://tamyla.com,https://*.tamyla.com"
MAGIC_LINK_EXPIRY_MINUTES = "15"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX = "100"
MAX_FILE_SIZE = "26214400"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,video/webm,audio/mpeg,audio/wav"
