name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        if: ${{ github.event_name == 'push' }}

      - name: Check build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build output not found"
            exit 1
          fi

      - name: Deploy with Cloudflare Wrangler
        uses: cloudflare/wrangler-action@v3.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          name: mongodb-worker
          env: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        env:
          NODE_ENV: production
        if: ${{ github.event_name == 'push' }}

      - name: Deploy preview on pull request
        if: ${{ github.event_name == 'pull_request' }}
        uses: cloudflare/wrangler-action@v3.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          name: mongodb-worker
          env: staging